### ISSUE TITLE
Diffing algorithm breaks with comments between rules

### ISSUE THREAD

**Issue by tobiasso85** [SAP/less-openui5#105]
When the scoping Diff algorithm runs with comments between rules it breaks:

Sample:

**base.css** (generated from less)
```css
body {
  color: black;
}

a {
  color: black;
}

b {
  text-align: center;
}
```

**plus.css** (generated from less)
```css
body {
  color: blue;
}
/* ============================= */
/* Shared CSS 1 theme            */
/* ============================= */
#CSS_SCOPE_ROOT {
  color: orange;
}
/* ============================= */
/* Shared CSS 2 theme            */
/* ============================= */
a {
  color: blue;
}

b {
  text-align: center;
}
```

Error::
```js
 TypeError: Cannot read property 'length' of undefined
     at selectorEquals (less-openui5\lib\diff.js:23:23)
     at Diffing.diffRules (less-openui5\lib\diff.js:83:12)
     at Diffing.run (less-openui5\lib\diff.js:140:37)
     at diff (less-openui5\lib\diff.js:150:38)
     at applyScope (less-openui5\lib\index.js:319:19)
     at less-openui5\lib\index.js:350:35
```
